version: '3'
services:

  redis:
    container_name: redis
    hostname: redis
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
      
  dimi-mysql:
    image: mysql:8.0.25
    container_name: talita-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=talita
      - MYSQL_ROOT_PASSWORD=talitadb
    volumes:
      - ./database/mysql-db:/docker-entrypoint-initdb.d
      - ./database/storage/.db:/var/lib/mysql
